apiVersion: v1
kind: Config
users:
- name: percona-xtradb-cluster-operator
  user:
    token: {TOKEN}
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: {SERVER_INFO}
  name: self-hosted-cluster
contexts:
- context:
    cluster: self-hosted-cluster
    user: percona-xtradb-cluster-operator
  name: percona-xtradb-cluster-context
current-context: percona-xtradb-cluster-context