scrape_configs:
- job_name: blackbox80
  params:
    module:
    - http_2xx
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http

  static_configs:
  - targets:
    - http://www.alfaexploit.com/archive

  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - source_labels: [__param_target]
    target_label: node_name
  - target_label: __address__
    replacement: pmm.alfaexploit.com:9115
